### ISSUE TITLE
Add a config-import job to verify dependency updates

### ISSUE THREAD

**Issue by mglaman** [simplytestme/website#191]
Dependency updates may have schema changes that change the configuration, and they need to be re-exported. We need a pipeline job for this.

Here is the one I use for my blog

```yaml
  verify_config:
    name: Verify config changes
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
            MYSQL_DATABASE: ci
        ports:
            - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          ref: 'master'

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: 8.1
          extensions: zip, gd
          tools: composer:v2

      - name: Composer install original dependencies
        run: composer install

      - run: cp .github/ci.settings.php web/sites/default/settings.local.php

      - name: Install baseline
        run: ./bin/drush site-install --yes
        env:
            DB_PORT: ${{ job.services.mysql.ports[3306] }}

      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          clean: false

      - name: Composer install new dependencies
        run: composer install

      # - name: Clear container cache
      #   run: ./bin/drush sql:query "DELETE FROM cache_container;" -vvv

      - name: Run updates on new branch
        run: ./bin/drush updb -y
        env:
            DB_PORT: ${{ job.services.mysql.ports[3306] }}

      - name: Import config on new branch
        run: ./bin/drush cim -y
        env:
            DB_PORT: ${{ job.services.mysql.ports[3306] }}

      - name: Check for config changes on new branch
        run: ./bin/drush config:status 2>&1 | grep "No differences"
        env:
            DB_PORT: ${{ job.services.mysql.ports[3306] }}

      - name: Verify cache rebuild does not crash
        run: ./bin/drush cr
        env:
            DB_PORT: ${{ job.services.mysql.ports[3306] }}
```

This is the `ci.settings.php` content

```php
<?php

$databases['default']['default'] = [
  'database' => 'ci',
  'username' => 'root',
  'password' => '',
  'host' => '127.0.0.1',
  'driver' => 'mysql',
  'port' => getenv('DB_PORT'),
  'prefix' => '',
];

$settings['skip_permissions_hardening'] = TRUE;

$settings['hash_salt'] = '46iWqQXD6OezGhR2nGBRnfd3a7rTq0UlOlkar2GEd_RDcbTv7apVV1bycVMLHqlMj2cBf7pf1Q';
```
